on:
  push:

jobs:
  setup_environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

  check_code_syntax:
    runs-on: ubuntu-latest
    needs: setup_environment
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Run Ruff
        run: |
          ruff check

  run_tests:
    runs-on: ubuntu-latest
    needs: setup_environment
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run pytest
        run: |
          pytest

  build_and_push:
    runs-on: ubuntu-latest
    needs: [ check_code_syntax, run_tests ]
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            weltraumpenner/mydealz_bot:${{ github.run_number }}
            weltraumpenner/mydealz_bot:latest
            ${{ github.ref == 'refs/heads/master' && 'weltraumpenner/mydealz_bot:stable' || '' }}
